myproject/urls.py
from django.conf.urls import url,include
from django.http import HttpResponseRedirect
from django.contrib import admin
from django.conf import settings
from django.views.generic import RedirectView


admin.autodiscover()

urlpatterns = [
    url(r'^$', lambda x: HttpResponseRedirect('/resizer/index/')),
    url(r'^resizer/',include('resizer.urls')),
    url(r'^admin/', include(admin.site.urls)),

]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resizer/urls.py
from django.conf.urls import url

import views as views

app_name = 'resizer'

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^resizer_op/$', views.resizer_op, name='resizer_op'),
    url(r'^resize_op_fetch_param/$', views.resize_op_fetch_param, name='resize_op_fetch_param'),
    url(r'^compress_op/$',views.compress_op,name='compress_op'),
    url(r'^compress_op_fetch_param/$',views.compress_op_fetch_param,name='compress_op_fetch_param'),
    url(r'^enhance_op/$',views.enhance_op,name='enhance_op'),
    url(r'^enhance_op_fetch_param/$', views.enhance_op_fetch_param, name='enhance_op_fetch_param'),

]

resizer/models.py
from __future__ import unicode_literals

from django.db import models

class Document(models.Model):
    docfile = models.FileField(upload_to='documents/%Y/%m/%d')

class Opencv(models.Model):
    imagem = models.ImageField(upload_to='documents/')

class Opencv2(models.Model):
    height = models.CharField(max_length=100,help_text="Enter height in px")
    width = models.CharField(max_length=100,help_text="Enter width in px")
    resize_method = models.CharField(max_length=255,help_text="Enter method for resizing")

resizer/forms.py
from django.forms import forms
from django.forms import ModelForm
from .models import Opencv, Opencv2


class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file'
    )

class FormOpencv(ModelForm):
    class Meta:
        model = Opencv
        fields = ['imagem']


class ResizerInputs(ModelForm):
    class Meta:
        model = Opencv2
        fields = ['height','width','resize_method']

resizer/views.py
import numpy as np
import cv2
import os
from PIL import Image as Im


from django.http import HttpResponse,HttpResponseRedirect
from .models import  Document,Opencv, Opencv2
from .forms import DocumentForm,FormOpencv,ResizerInputs
from django.shortcuts import render
from django.core.urlresolvers import reverse
from .Processor import worker

img_path=''
wk = worker()
def index(request):
    # Handle file upload
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            newdoc = Document(docfile=request.FILES['docfile'])
            newdoc.save()

            # Redirect to the document list after POST
            return HttpResponseRedirect(reverse('resizer:index'))
    else:
        form = DocumentForm()  # A empty, unbound form

    # Load documents for the list page
    documents = Document.objects.all()

    # Render list page with the documents and the form
    return render(
        request,
        'resizer/index.html',
        {'documents': documents, 'form': form}
    )

def resizer_op(request):
    return resizer_op_fetch_img(request)
def compress_op(request):
    return compress_op_fetch_img(request)
def enhance_op(request):
    return enhance_op_fetch_img(request)


def resizer_op_fetch_img(request):
    form = FormOpencv(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = Opencv(imagem = request.FILES['imagem'])
        obj.save()
        image_path = get_Image_path(obj)
        data = True

        return render(request, 'resizer/forms.html', {'form': form, 'data': data})
    else:
        form = FormOpencv()


    return render(request,'resizer/forms.html',{'form':form})

def resize_op_fetch_param(request):
    #fetch all the parameters
    h = request.POST.get('height')
    w = request.POST.get('width')
    m = request.POST.get('resize_method')
    global img_path
    height = int(h);weight=int(w);method=str(m)
    processed_img = wk.setResize(img_path,height,weight,True,method)
    cv2.imwrite("resizer/static/documents/resized_img.jpg",processed_img)
    data = True
    processed = True
    return render(request, 'resizer/forms.html',{'data': data,'processed':processed})

def compress_op_fetch_img(request):
    form = FormOpencv(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = Opencv(imagem=request.FILES['imagem'])
        obj.save()
        global image_path
        image_path = get_Image_path(obj)
        data = True

        return render(request, 'resizer/compress_form.html', {'form': form, 'data': data})
    else:
        form = FormOpencv()

    return render(request, 'resizer/compress_form.html', {'form': form})


def compress_op_fetch_param(request):
    size = request.POST.get('size')
    print size
    s = int(size)
    global img_path
    print img_path
    compressed_img = wk.CompressorController(img_path,s)

    data = True
    processed = True
    return render(request, 'resizer/compress_form.html', {'data': data, 'processed': processed})

def enhance_op_fetch_img(request):
    form = FormOpencv(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = Opencv(imagem=request.FILES['imagem'])
        obj.save()
        image_path = get_Image_path(obj)
        data = True

        return render(request, 'resizer/enhance_form.html', {'form': form, 'data': data})
    else:
        form = FormOpencv()
    return render(request, 'resizer/enhance_form.html', {'form': form})


def enhance_op_fetch_param(request):
    Brightness = request.POST.get('Brightness')
    gamma = request.POST.get('gamma')
    Sharpeness = request.POST.get('Sharpeness')
    sharpen_method = request.POST.get('sharpen_method')
    Contrast = request.POST.get('Contrast')
    EqualizeHist  = request.POST.get('EqualizeHist')
    print Brightness,gamma,sharpen_method,Sharpeness,Contrast,EqualizeHist
    if os.path.isfile('resizer/static/documents/enhanced_img.jpg'):
        try:
            os.remove('resizer/static/documents/enhanced_img.jpg')
            print "Successfully Deleted"
        except OSError:
            pass
    global img_path
    path_res = img_path
    b = float(Brightness)
    if b <= 0 :
        if gamma==1:g=True
        else: g = False
        brighten_img = wk.setBrightness(img_path,b,g,True)
        path_res = 'resizer/static/documents/enhanced_img.jpg'
        cv2.imwrite(path_res,brighten_img)

    s = int(Sharpeness)
    if s<=0:
        s_m = int(sharpen_method)
        sharpen_img = wk.setSharpen(path_res,s,s_m)
        path_res = 'resizer/static/documents/enhanced_img.jpg'
        cv2.imwrite(path_res, sharpen_img)

    c = int(Contrast)
    if c<=0:
        print "In contrast"
        if EqualizeHist==1:e_h=True
        else:e_h=False
        contrast_img = wk.setContrast(path_res,c,e_h,True)
        path_res = 'resizer/static/documents/enhanced_img.jpg'
        cv2.imwrite(path_res, contrast_img)
    data = True
    processed = True
    return render(request, 'resizer/enhance_form.html', {'data': data, 'processed': processed})

def get_Image_path(obj):
    img_db = obj.imagem
    print img_db
    img_read = img_db.read()
    img_np = np.asarray(bytearray(img_read),dtype="uint8")
    img_op = cv2.imdecode(img_np,cv2.IMREAD_UNCHANGED)

    #delete the previous temp files
    if os.path.isfile('resizer/static/documents/temp_img.jpg'):
        try:
            os.remove('resizer/static/documents/temp_img.jpg')
            print "Successfully Deleted"
        except OSError:
            pass

    #Create a local_temp file for processing
    cv2.imwrite('resizer/static/documents/temp_img.jpg',img_op)
    global  img_path
    img_path = 'resizer/static/documents/temp_img.jpg'

    return img_path

resizer/templates/fileupload/picture_basic_form.html
<!DOCTYPE HTML>
<html lang="en">
<head>
<!-- Force latest IE rendering engine or ChromeFrame if installed -->
<!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><![endif]-->
<meta charset="utf-8">
<title>Django jQuery File Upload Demo - Basic version</title>
<meta name="description" content="File Upload widget with multiple file selection, drag&amp;drop support and progress bar for jQuery. Supports cross-domain, chunked and resumable file uploads. Works with any server-side platform (PHP, Python, Ruby on Rails, Java, Node.js, Go etc.) that supports standard HTML form file uploads.">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Bootstrap styles -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
<!-- Generic page styles -->
<link rel="stylesheet" href="/static/css/style.css">
<!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
<link rel="stylesheet" href="/static/css/jquery.fileupload-ui.css">
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-fixed-top .navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://github.com/sigurdga/django-jquery-file-upload">Django jQuery File Upload</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Demo</a></li>
                <li><a href="https://github.com/sigurdga/django-jquery-file-upload">Source Code</a></li>
                <li><a href="https://github.com/blueimp/jQuery-File-Upload/wiki">Documentation</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="container">
    <h1>Django jQuery File Upload Demo</h1>
    <h2 class="lead">Basic version</h2>
    <ul class="nav nav-tabs">
        <li class="active"><a href="/upload/basic">Basic</a></li>
        <li><a href="/upload/basic/plus">Basic Plus</a></li>
        <li><a href="/upload/new">Basic Plus UI</a></li>
        <li><a href="/upload/angular">AngularJS</a></li>
        <li><a href="/upload/jquery-ui">jQuery UI</a></li>
    </ul>
    <br>
    <blockquote>
        <p>File Upload widget with multiple file selection, drag&amp;drop support and progress bar for jQuery.<br>
        Supports cross-domain, chunked and resumable file uploads.</p>
    </blockquote>
    <br>
    <!-- The fileinput-button span is used to style the file input field as button -->
    <span class="btn btn-success fileinput-button">
        <i class="glyphicon glyphicon-plus"></i>
        <span>Select files...</span>
        <!-- The file input field used as target for the file upload widget -->
        <input id="fileupload" type="file" name="file" multiple>
    </span>
    <br>
    <br>
    <!-- The global progress bar -->
    <div id="progress" class="progress">
        <div class="progress-bar progress-bar-success"></div>
    </div>
    <!-- The container for the uploaded files -->
    <div id="files" class="files"></div>
    <br>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Demo Notes</h3>
        </div>
        <div class="panel-body">
            <ul>
                <li>You can <strong>drag &amp; drop</strong> files from your desktop on this webpage (see <a href="https://github.com/blueimp/jQuery-File-Upload/wiki/Browser-support">Browser support</a>).</li>
                <li>Please refer to the <a href="https://github.com/blueimp/jQuery-File-Upload">project website</a> and <a href="https://github.com/blueimp/jQuery-File-Upload/wiki">documentation</a> for more information.</li>
                <li>Built with Twitter's <a href="http://twitter.github.com/bootstrap/">Bootstrap</a> CSS framework and Icons from <a href="http://glyphicons.com/">Glyphicons</a>.</li>
            </ul>
        </div>
    </div>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<script src="/static/js/vendor/jquery.ui.widget.js"></script>
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<script src="/static/js/jquery.iframe-transport.js"></script>
<!-- The basic File Upload plugin -->
<script src="/static/js/jquery.fileupload.js"></script>
<!-- Bootstrap JS is not required, but included for the responsive demo navigation -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="/static/js/jquery.cookie.js"></script>
<script>
/*jslint unparam: true */
/*global window, $ */
function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$(function () {
    'use strict';
    // Change this to the location of your server-side upload handler:
    var url = '/upload/basic/';
    var csrftoken = $.cookie('csrftoken');
    $('#fileupload').fileupload({
        url: url,
        crossDomain: false,
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type)) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        },
        dataType: 'json',
        done: function (e, data) {
            $.each(data.result.files, function (index, file) {
                $('<p/>').text(file.name).appendTo('#files');
            });
        },
        progressall: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('#progress .progress-bar').css(
                'width',
                progress + '%'
            );
        }
    }).prop('disabled', !$.support.fileInput)
        .parent().addClass($.support.fileInput ? undefined : 'disabled');
});
</script>
</body> 
</html>

resizer/templates/resizer/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>{%block title %}Home -Resizer{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'PIXSOL/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'PIXSOL/js/main.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
         	<!--HEADER-->

			<div class="navbar-header">
            	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'resizer:index' %}">PIXSOL<sub>(beta)</sub></a>

            </div>
 <div class="collapse navbar-collapse" id="topNavBar">
 <ul class="nav navbar-nav">
 	<li class="{% block resize_active %}{% endblock %}"><a href="{% url 'resizer:resizer_op' %}"><span class="glyphicon glyphicon-resize-small" aria-hidden="true"></span>&nbsp; Resize</a></li>
    <li class="{% block compress_active %}{% endblock %}"><a href="{% url 'resizer:compress_op' %}"><span class="glyphicon glyphicon-scissors" aria-hidden="true"></span>&nbsp; Compress</a></li>
    <li class="{% block enhance_active %}{% endblock %}"><a href="#"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp; Enhance</a></li>
   </ul>
   </div>
   </div>
   </nav>
   {% block content %}
   {% endblock %}
</body>
</html>

resizer/templates/resizer/compress_form.html
{% extends "resizer/base.html" %}
{% load static %}
{% block title %} Compress Image {% endblock %}
{% block content %}
<div class="container">
<header class="resize-pic">
	<h1><b> Compress Your Pic</b></h1>
	<p>
	<!-- A bitton for uploading the image-->
	<form action="{% url 'resizer:compress_op'  %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="media">
            <div class="media-left media-middle">
              <br>
              <br>
              <p>{{ form.non_field_errors }}</p>
              <p>
                  {{ form.imagem.errors }}
                  {{ form.imagem }}
              </p>

            </p>
                <input type="submit" value="Upload">

            </form>
            <br>
            </div>
            </div>

</header>
</div>
{% if data %}
<div class="image_op_resize">
<h3><b> Enter Parameters for Resizing</b></h3>
    <div class="Original_img">
        <img style="width: 200px; height: 100 px" src="{% static 'documents/temp_img.jpg' %}" alt="Error Processing"/>
        <form action="{% url 'resizer:compress_op_fetch_param' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <br>Size(in KB):
            <input name="size" type="text" />

            <input type="submit" value="OK"/>
        </form>
    <p><h4>The backend compression code is bit buggy ,<br> kindly ignore using it for now.<hr></h4></p>
    </div>
        {% if processed %}
    <div class="Compressed_image">
        The compressed image:<br>

        <img style="width: 200px; height: 100 px" src="{% static 'documents/compressed_img.jpg' %}" alt="Error Processing"/>
        <p>Just right click and save the image.<br>
        Enjoy!!<br>
    </div>
    {% endif %}
</div>
<hr>
{% endif %}

{% endblock %}

resizer/templates/resizer/enhance_form.html
{% extends "resizer/base.html" %}
{% load static %}
{% block title %} Enhance Image {% endblock %}
{% block content %}
<div class="container">
<header class="resize-pic">
	<h1><b> Enhance Your Pic</b></h1>
    <p>
    <h3> Brighten, sharpen, and set-contrast for the image</h3>
    </p>
	<p>
	<!-- A bitton for uploading the image-->
	<form action="{% url 'resizer:enhance_op'  %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="media">
            <div class="media-left media-middle">
              <br>
              <br>
              <p>{{ form.non_field_errors }}</p>
              <p>
                  {{ form.imagem.errors }}
                  {{ form.imagem }}
              </p>

            </p>
                <input type="submit" value="Upload">

            </form>
            <br>
            </div>
            </div>

</header>
</div>
{% if data %}
<div class="image_op_enhance">
<h3><b> <u>Enter Parameters for Enhancing Your Image</u></b></h3>

    <div class="Original_img">
        <img style="width: 480px; height: 360px" src="{% static 'documents/temp_img.jpg' %}" alt="Error Processing"/>
        <form action="{% url 'resizer:enhance_op_fetch_param' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p> <h5><u><strong>Brightness:</strong></u></h5>
            <input name = "Brightness" id="Brightness" type="range" min="0" max="300" value="0" step="5"
                   onchange="showValue(this.value)" style="-webkit-appearance: none;
            padding-left:2px; padding-right:2px;
            width:200px;
            -webkit-border-radius: 5px;
            background-image: -webkit-linear-gradient(top, #000000, #333333, #000000);" />
               <span id="range">0</span>
                <input type="checkbox" name="gamma" id="gamma" value="1" onchange="changeRange()"/> Gamma
                <br>
                <h5><u><strong>Sharpness: </h5></strong></u>
            <input name = "Sharpeness" type="range" min="0" max="100" value="0" step="5"
                   onchange="showValue1(this.value)" style="-webkit-appearance: none;
            padding-left:2px; padding-right:2px;
            width:200px;
            -webkit-border-radius: 5px;
            background-image: -webkit-linear-gradient(top, #000000, #333333, #000000);" />
                <span id="range1">0</span>
                Select Method:
                <select name="sharpen_method" >
                    <option value = "1">simple_sharpening</option>
                    <option value = "2">excessive_sharpening</option>
                    <option value = "3">Edge_sharpening</option>
                    <option value = "4">Gaussian Unsgarp Masking</option>
            </select>
                <br>
                <h5><u><strong>Contrast: </h5></strong></u>
            <input name = "Contrast" type="range" min="0" max="100" value="0" step="5"
                   onchange="showValue2(this.value)" style="-webkit-appearance: none;
            padding-left:2px; padding-right:2px;
            width:200px;
            -webkit-border-radius: 5px;
            background-image: -webkit-linear-gradient(top, #000000, #333333, #000000);" />
            <span id="range2">0</span>
                <input type="checkbox" name="EqualizeHist" value="1"> Equalize Histogram

                <br>
            </p>
            <input type="submit" value="OK"/>

            </form>
    </div>
</div>
 {% if processed %}
    <div class="enhanced_image">
        The compressed image:<br>

        <img style="width: 480px; height: 360px" src="{% static 'documents/enhanced_img.jpg' %}" alt="Error Processing"/>
        <p>Just right click and save the image.<br>
        Enjoy!!<br>
    </div>
    {% endif %}
</div>
<hr>
{% endif %}
<script type="text/javascript">
            function changeRange()
            {
                if(document.getElementById("gamma").checked==true)
                {
                    document.getElementById("Brightness").min=0;
                    document.getElementById("Brightness").step=0.5;
                    document.getElementById("Brightness").max=3.5;
                     document.getElementById("Brightness").value=0;
                }
                else
                {
                    document.getElementById("Brightness").min=0;
                     document.getElementById("Brightness").step=10;
                    document.getElementById("Brightness").max=300;
                     document.getElementById("Brightness").value=0;
                }
                showValue(0);
            }
            function showValue(newValue)
            {
                document.getElementById("range").innerHTML=newValue;
            }
            function showValue1(newValue)
            {
                document.getElementById("range1").innerHTML=newValue;
            }
            function showValue2(newValue)
            {
                document.getElementById("range2").innerHTML=newValue;
            }
            </script>
{% endblock %}

resizer/templates/resizer/forms.html
{% extends "resizer/base.html" %}
{% load static %}
{% block title %} Resize Image {% endblock %}
{% block content %}
<div class="container">
<header class="resize-pic">
	<h1><b> Resize Your Pic</b></h1>
	<p>
	<!-- A bitton for uploading the image-->
	<form action="{% url 'resizer:resizer_op'  %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="media">
            <div class="media-left media-middle">
              <br>
              <br>
              <p>{{ form.non_field_errors }}</p>
              <p>
                  {{ form.imagem.errors }}
                  {{ form.imagem }}
              </p>

            </p>
                <input type="submit" value="Upload">

            </form>
            <br>
            </div>
            </div>

</header>
</div>
{% if data %}
<div class="image_op_resize">
<h3><b> Enter Parameters for Resizing</b></h3>
    <div class="Original_img">
        <img style="width: 200px; height: 100 px" src="{% static 'documents/temp_img.jpg' %}" alt="Error Processing"/>
        <form action="{% url 'resizer:resize_op_fetch_param' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <br>Height(in px):
            <input name="height" type="text" />

            <br>
            Width(in px):
            <input name="width" type="text" />

            <br>
            Select Method:
            <select name="resize_method" >
                <option value = "cv2.INTER_NEAREST">INTER_NEAREST</option>
                <option value = "cv2.INTER_LINEAR">INTER_LINEAR</option>
                <option value = "cv2.INTER_AREA">INTER_AREA</option>
                <option value = "cv2.INTER_LANCZOS4">INTER_LANCZOS4</option>
                <option value = "cv2.INTER_CUBIC">Auto</option>
            </select>
            <br>
            <input type="submit" value="OK"/>
        </form>

    </div>
        {% if processed %}
    <div class="Negative_image">
        The resized image:<br>

        <img style="width: 200px; height: 100 px" src="{% static 'documents/resized_img.jpg' %}" alt="Error Processing"/>
        <p>Just right click and save the image.<br>
        Enjoy!!<br>
    </div>
    {% endif %}
</div>
<hr>
{% endif %}
{% endblock %}

resizer/templates/resizer/index.html
{% extends 'resizer/base.html' %}

{% block title %} Home-Upload Image {% endblock %}

{% block content %}
 <div class="container">
<header class="resize-pic">
    <p><h4>Welocome to demonstration of Opencv and PIL based Image operations.<br>
    This is an attempt to show usage of Opencv on web based Framework.
    </h4>
    </p>
    <hr>
    <p>
        <h6>You can start by directly uploading a pic on this page , <br>
        or make use of navigation bar
    </h6>
    </p>
	<h1><b> Resize Your Pic</b></h1>
	<p>
	<!-- A bitton for uploading the image-->
	<form action="{% url 'resizer:resizer_op'  %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="media">
            <div class="media-left media-middle">
              <br>
              <br>
              <p>{{ form.non_field_errors }}</p>
              <p>
                  {{ form.imagem.errors }}
                  {{ form.imagem }}
              </p>

            </p>
                <input type="submit" value="Upload">

            </form>
            <br>
            </div>
            </div>

</header>
</div>
{% endblock %}

resizer/templates/resizer/postForm.html
{% extends "base.html" %}
{% block body %}
    <div class="containerImage">
        <h1>Form</h1>
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" class="btn btn-default" value="Upload">

        </form>
    </div>

{% endblock %}

resizer/templates/upload_base.html
<!DOCTYPE HTML>
<html lang="en">
<head>
    <!-- Force latest IE rendering engine or ChromeFrame if installed -->
    <!--[if IE]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <![endif]-->
    <meta charset="utf-8">
    <title>Django Jquery file upload demo</title>
    <meta name="description" content="File Upload widget with multiple file selection, drag&amp;drop support, progress bars, validation and preview images, audio and video for jQuery. Supports cross-domain, chunked and resumable file uploads and client-side image resizing. Works with any server-side platform (PHP, Python, Ruby on Rails, Java, Node.js, Go etc.) that supports standard HTML form file uploads.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap styles -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
    <!-- Generic page styles -->
    <link rel="stylesheet" href="/static/css/style.css">
    <!-- blueimp Gallery styles -->
    <link rel="stylesheet" href="/static/css/blueimp-gallery.min.css">
    <!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
    <link rel="stylesheet" href="/static/css/jquery.fileupload-ui.css">
    <!-- CSS adjustments for browsers with JavaScript disabled -->
    <noscript><link rel="stylesheet" href="/static/css/jquery.fileupload-ui-noscript.css"></noscript>
    
    <!-- Shim to make HTML5 elements usable in older Internet Explorer versions -->
    <!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-fixed-top .navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://github.com/sigurdga/django-jquery-file-upload">Django jQuery File Upload</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Demo</a></li>
                <li><a href="https://github.com/sigurdga/django-jquery-file-upload">Source Code</a></li>
                <li><a href="https://github.com/blueimp/jQuery-File-Upload/wiki">Documentation</a></li>
            </ul>
        </div>
    </div>
</div>

{% block content %}
    <h1>No content set</h1>
{% endblock %}

</body> 
</html>